language: c
sudo: false

addons:
  apt:
    packages:
      - python3-pip
      - python3-wheel

script:
  - build_main_platforms
  
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
